# model
LATENT_DIM = 10
LEARNING_RATE = .1
WEIGHTS_REGULAR = .001
INITIAL_THETA_SCALE = .2

# offline training
OFFLINE_TRAINING_EPOCHS = 1000
OFFLINE_SAMPLE_TRAINING_EPOCHS = 2
OFFLINE_BATCH_SIZE = 100000
OFFLINE_EARLY_STOP_THRESHOLD = 0.1

# performance
THREADS = 4
